# Generated by Django 4.2.10 on 2024-03-05 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_postmedia_updated_at_postmention_updated_at_and_more'),
        ('user_activity', '0003_storylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storylike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='storylike',
            unique_together={('user', 'story')},
        ),
    ]
