# Generated by Django 4.2.10 on 2024-03-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_postmedia_updated_at_postmention_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes_count_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'image'), ('VIDEO', 'video')], default='IMAGE', max_length=5),
            preserve_default=False,
        ),
    ]
