# Generated by Django 4.2.10 on 2024-03-05 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0005_story_likes_count_display_story_media_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at'], 'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='type',
            field=models.CharField(blank=True, choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='storymention',
            unique_together={('story', 'user')},
        ),
    ]
