# Generated by Django 4.2.10 on 2024-03-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
